### ISSUE TITLE
Duplicate sources 

### ISSUE THREAD

**Issue by Mr-invisibles** [host505/repository.host505#1]
Hey 
Not a direct issue,  but I see if I add some more/other torrent scrapers duplicate sources filter won't work.. 
Or have you added some other code in your used scrapers? 

Would just be great to be able to add some more and still use duplicate filters.. 

Best regards

**Comment by host505** [comment]
I noticed it doesn't work with openscrapers too.
I did add some torrent-related code to the dupes checker recently (to check infohash instead of url on torrents so it can remove duplicate magnets).
I did some debugging, and long story short the culprit seems to be the mkvcage torrent provider. Is that one of those you add?
I noticed it modifies the magnet link before supplying it to the add-on, and the infohash parsing I introduced doesn't work.
I'll see if I can make some sort of exception for this.
Thanks for bringing it to my attention.

**Comment by Mr-invisibles** [comment]
Hey
Yes mkvcage it's 1 of the Scrapers i added, can try just remove that one and check if its starting to work again,
this torrent scrapers i tried to add. 
-mkvcage
-piratebay
-skytorrents
-torrentquest
-yifyddl

Will try remove mkv and check

**Comment by host505** [comment]
fyi:
-piratebay, I already have (tpb, probably another variation)
-torrentquest is a sister site to magnetdl which I already have (same links). I discovered and used that when magnetdl went down (now it's up again)
-yifyddl's links are probably the same as ytsam's

**Comment by Mr-invisibles** [comment]
yea was looking in to them and seems right what you say :) 
so may not need to add anyone. 
well thx indeed for the none problem solution :)

**Comment by host505** [comment]
Did removing mkvcage fix the problem for you too?
What I said before was wrong, the scraper doesn't modify the magnet link, it's the site supplying a form of magnet links not covered by the regex I used to parse infohash.
Will have to work on that to cover that magnet variation.

**Comment by Mr-invisibles** [comment]
yes it works when remove mkvcage, or needed to remove all i added, but no need to add them when it's just duplicates "typ"

**Comment by host505** [comment]
fixed: https://github.com/host505/plugin.video.theoath/commit/38c08e60eb37d61a33c5f4ad3b5aed327bf4a803
